return {
  version = "1.5",
  luaversion = "5.1",
  tiledversion = "1.8.2",
  orientation = "orthogonal",
  renderorder = "right-up",
  width = 23,
  height = 50,
  tilewidth = 64,
  tileheight = 64,
  nextlayerid = 6,
  nextobjectid = 191,
  properties = {
    ["playerstartingx"] = 11,
    ["playerstartingy"] = 48
  },
  tilesets = {
    {
      name = "map",
      firstgid = 1,
      tilewidth = 64,
      tileheight = 64,
      spacing = 0,
      margin = 0,
      columns = 10,
      image = "../assets/images/tilesets/map.png",
      imagewidth = 640,
      imageheight = 256,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 64,
        height = 64
      },
      properties = {},
      wangsets = {},
      tilecount = 40,
      tiles = {}
    },
    {
      name = "Objets",
      firstgid = 41,
      tilewidth = 104,
      tileheight = 100,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 48,
      tiles = {
        {
          id = 0,
          image = "../assets/images/misc/barrelBlack_side.png",
          width = 40,
          height = 56
        },
        {
          id = 1,
          image = "../assets/images/misc/barrelBlack_top.png",
          width = 48,
          height = 48
        },
        {
          id = 2,
          image = "../assets/images/misc/barrelGreen_side.png",
          width = 40,
          height = 56
        },
        {
          id = 3,
          image = "../assets/images/misc/barrelGreen_top.png",
          width = 48,
          height = 48
        },
        {
          id = 4,
          image = "../assets/images/misc/barrelRed_side.png",
          width = 40,
          height = 56
        },
        {
          id = 5,
          image = "../assets/images/misc/barrelRed_top.png",
          width = 48,
          height = 48
        },
        {
          id = 6,
          image = "../assets/images/misc/barrelRust_side.png",
          width = 40,
          height = 56
        },
        {
          id = 7,
          image = "../assets/images/misc/barrelRust_top.png",
          width = 48,
          height = 48
        },
        {
          id = 8,
          image = "../assets/images/misc/barricadeMetal.png",
          width = 56,
          height = 56
        },
        {
          id = 9,
          image = "../assets/images/misc/barricadeWood.png",
          width = 56,
          height = 56
        },
        {
          id = 10,
          image = "../assets/images/misc/crateMetal.png",
          width = 56,
          height = 56
        },
        {
          id = 11,
          image = "../assets/images/misc/crateWood.png",
          width = 56,
          height = 56
        },
        {
          id = 12,
          image = "../assets/images/misc/fenceRed.png",
          width = 96,
          height = 32
        },
        {
          id = 13,
          image = "../assets/images/misc/fenceYellow.png",
          width = 104,
          height = 32
        },
        {
          id = 14,
          image = "../assets/images/misc/oilSpill_large.png",
          width = 100,
          height = 100
        },
        {
          id = 15,
          image = "../assets/images/misc/oilSpill_small.png",
          width = 28,
          height = 28
        },
        {
          id = 16,
          image = "../assets/images/misc/sandbagBeige_open.png",
          width = 84,
          height = 55
        },
        {
          id = 17,
          image = "../assets/images/misc/sandbagBeige.png",
          width = 64,
          height = 44
        },
        {
          id = 18,
          image = "../assets/images/misc/sandbagBrown_open.png",
          width = 84,
          height = 55
        },
        {
          id = 19,
          image = "../assets/images/misc/sandbagBrown.png",
          width = 64,
          height = 44
        },
        {
          id = 20,
          image = "../assets/images/misc/treeBrown_large.png",
          width = 64,
          height = 64
        },
        {
          id = 21,
          image = "../assets/images/misc/treeBrown_twigs.png",
          width = 52,
          height = 44
        },
        {
          id = 22,
          image = "../assets/images/misc/wireCrooked.png",
          width = 44,
          height = 48
        },
        {
          id = 23,
          image = "../assets/images/misc/wireStraight.png",
          width = 17,
          height = 70
        },
        {
          id = 24,
          image = "../assets/images/misc/treeBrown_leaf.png",
          width = 8,
          height = 10
        },
        {
          id = 25,
          image = "../assets/images/misc/treeBrown_small.png",
          width = 36,
          height = 36
        },
        {
          id = 26,
          image = "../assets/images/misc/treeGreen_leaf.png",
          width = 8,
          height = 10
        },
        {
          id = 27,
          image = "../assets/images/misc/treeGreen_twigs.png",
          width = 26,
          height = 22
        },
        {
          id = 28,
          image = "../assets/images/misc/tile_134.png",
          width = 64,
          height = 64
        },
        {
          id = 29,
          image = "../assets/images/misc/tile_210.png",
          width = 64,
          height = 64
        },
        {
          id = 30,
          image = "../assets/images/misc/tile_213.png",
          width = 64,
          height = 64
        },
        {
          id = 31,
          image = "../assets/images/misc/tile_235.png",
          width = 64,
          height = 64
        },
        {
          id = 32,
          image = "../assets/images/misc/tile_236.png",
          width = 64,
          height = 64
        },
        {
          id = 33,
          image = "../assets/images/misc/tile_237.png",
          width = 64,
          height = 64
        },
        {
          id = 34,
          image = "../assets/images/misc/tile_238.png",
          width = 64,
          height = 64
        },
        {
          id = 35,
          image = "../assets/images/misc/tile_239.png",
          width = 64,
          height = 64
        },
        {
          id = 36,
          image = "../assets/images/misc/tile_240.png",
          width = 64,
          height = 64
        },
        {
          id = 37,
          image = "../assets/images/misc/tile_265.png",
          width = 64,
          height = 64
        },
        {
          id = 38,
          image = "../assets/images/misc/tile_266.png",
          width = 64,
          height = 64
        },
        {
          id = 39,
          image = "../assets/images/misc/tile_316.png",
          width = 64,
          height = 64
        },
        {
          id = 40,
          image = "../assets/images/misc/tile_317.png",
          width = 64,
          height = 64
        },
        {
          id = 41,
          image = "../assets/images/misc/tile_318.png",
          width = 64,
          height = 64
        },
        {
          id = 42,
          image = "../assets/images/misc/tile_319.png",
          width = 64,
          height = 64
        },
        {
          id = 43,
          image = "../assets/images/misc/tile_320.png",
          width = 64,
          height = 64
        },
        {
          id = 44,
          image = "../assets/images/misc/tile_359.png",
          width = 64,
          height = 64
        },
        {
          id = 45,
          image = "../assets/images/misc/tile_360.png",
          width = 64,
          height = 64
        },
        {
          id = 46,
          image = "../assets/images/misc/treeGreen_large.png",
          width = 64,
          height = 64
        },
        {
          id = 47,
          image = "../assets/images/misc/treeGreen_small.png",
          width = 36,
          height = 36
        }
      }
    },
    {
      name = "Enemis",
      firstgid = 89,
      tilewidth = 46,
      tileheight = 42,
      spacing = 0,
      margin = 0,
      columns = 0,
      objectalignment = "unspecified",
      tileoffset = {
        x = 0,
        y = 0
      },
      grid = {
        orientation = "orthogonal",
        width = 1,
        height = 1
      },
      properties = {},
      wangsets = {},
      tilecount = 1,
      tiles = {
        {
          id = 0,
          image = "../assets/images/tanks/tank_blue.png",
          width = 46,
          height = 42
        }
      }
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 23,
      height = 50,
      id = 1,
      name = "Sols",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        11, 2, 1, 11, 1, 11, 11, 11, 1, 11, 11, 11, 1, 11, 11, 11, 1, 1, 1, 11, 11, 11, 11,
        3, 12, 3, 3, 3, 3, 3, 3, 3, 3, 3, 7, 3, 15, 1, 1, 11, 1, 11, 1, 11, 11, 11,
        1, 2, 1, 1, 1, 11, 1, 11, 11, 11, 1, 2, 11, 2, 11, 11, 11, 11, 1, 11, 1, 11, 11,
        1, 16, 3, 3, 3, 3, 3, 15, 1, 1, 1, 2, 1, 16, 3, 3, 3, 3, 3, 3, 15, 11, 1,
        11, 11, 1, 1, 11, 1, 11, 2, 1, 1, 11, 2, 11, 11, 1, 1, 1, 11, 1, 1, 2, 1, 11,
        11, 11, 11, 1, 1, 11, 1, 2, 1, 11, 11, 2, 1, 11, 1, 1, 1, 11, 11, 1, 2, 1, 11,
        1, 14, 3, 3, 3, 3, 3, 6, 3, 3, 3, 12, 3, 3, 3, 3, 15, 1, 1, 1, 2, 1, 1,
        1, 2, 1, 11, 11, 11, 11, 11, 11, 1, 11, 2, 1, 11, 1, 14, 6, 15, 1, 1, 2, 11, 11,
        1, 2, 1, 11, 11, 1, 1, 11, 1, 1, 11, 2, 11, 1, 11, 2, 1, 2, 11, 1, 2, 11, 1,
        1, 16, 3, 3, 3, 3, 3, 15, 11, 11, 11, 2, 1, 1, 1, 16, 3, 17, 11, 1, 2, 1, 1,
        1, 11, 1, 11, 11, 1, 1, 2, 1, 1, 1, 2, 1, 11, 1, 11, 11, 11, 1, 1, 2, 1, 11,
        1, 11, 11, 11, 11, 11, 1, 2, 11, 11, 11, 2, 1, 1, 1, 1, 11, 1, 11, 11, 2, 1, 11,
        1, 14, 3, 3, 3, 3, 3, 17, 1, 1, 1, 2, 11, 11, 1, 11, 1, 11, 1, 1, 2, 1, 1,
        11, 2, 1, 1, 11, 11, 11, 1, 11, 1, 1, 16, 3, 3, 3, 3, 3, 3, 3, 3, 6, 3, 3,
        11, 2, 1, 11, 11, 11, 11, 1, 1, 11, 1, 11, 1, 11, 1, 11, 11, 11, 1, 11, 1, 1, 11,
        1, 2, 11, 1, 11, 1, 1, 11, 1, 11, 11, 11, 11, 1, 11, 11, 11, 1, 11, 1, 1, 11, 1,
        1, 2, 11, 1, 11, 1, 11, 11, 1, 1, 1, 1, 14, 3, 3, 3, 3, 3, 3, 3, 3, 15, 11,
        11, 2, 11, 11, 1, 1, 1, 1, 1, 11, 11, 11, 2, 11, 1, 11, 1, 1, 11, 1, 11, 2, 11,
        11, 2, 11, 1, 11, 1, 11, 1, 1, 1, 1, 11, 2, 11, 11, 11, 11, 1, 11, 1, 11, 2, 1,
        1, 2, 11, 11, 11, 11, 11, 11, 11, 1, 1, 11, 2, 1, 11, 11, 11, 1, 1, 1, 11, 2, 11,
        11, 2, 1, 1, 11, 1, 1, 11, 1, 11, 1, 11, 2, 11, 11, 1, 1, 11, 11, 11, 11, 2, 11,
        11, 2, 1, 1, 11, 11, 1, 1, 11, 1, 11, 1, 2, 11, 1, 11, 11, 11, 1, 1, 11, 2, 1,
        1, 2, 11, 11, 1, 11, 11, 11, 11, 1, 1, 1, 2, 1, 11, 1, 14, 3, 3, 3, 3, 17, 11,
        1, 2, 11, 11, 11, 11, 11, 1, 1, 11, 1, 11, 2, 1, 1, 1, 2, 1, 11, 11, 1, 11, 1,
        1, 2, 1, 11, 1, 1, 11, 11, 1, 11, 11, 1, 2, 11, 1, 1, 2, 1, 11, 1, 1, 11, 11,
        1, 16, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 5, 11, 1, 1, 2, 1, 11, 11, 11, 1, 1,
        11, 11, 1, 1, 11, 1, 1, 1, 11, 11, 11, 11, 2, 1, 1, 11, 2, 11, 11, 11, 11, 1, 1,
        1, 1, 11, 11, 11, 1, 11, 1, 1, 11, 11, 1, 2, 11, 1, 11, 2, 11, 1, 1, 11, 11, 1,
        1, 1, 14, 3, 3, 3, 3, 3, 3, 3, 3, 3, 6, 3, 3, 3, 6, 3, 3, 3, 3, 3, 3,
        11, 1, 2, 11, 1, 11, 11, 11, 11, 1, 1, 11, 1, 11, 1, 11, 11, 11, 1, 1, 1, 11, 11,
        11, 11, 2, 11, 1, 1, 11, 11, 1, 1, 1, 11, 11, 1, 1, 11, 1, 1, 11, 11, 11, 11, 1,
        1, 1, 2, 1, 11, 1, 1, 1, 1, 1, 1, 11, 1, 11, 11, 1, 11, 1, 11, 1, 1, 11, 11,
        1, 11, 2, 1, 1, 11, 11, 11, 1, 1, 1, 1, 11, 1, 1, 1, 11, 1, 1, 11, 11, 11, 1,
        11, 11, 2, 1, 11, 11, 1, 1, 1, 11, 11, 1, 11, 1, 11, 1, 1, 1, 11, 1, 11, 11, 1,
        1, 11, 2, 11, 11, 1, 11, 11, 1, 11, 14, 3, 3, 3, 3, 3, 3, 3, 3, 3, 15, 11, 1,
        11, 1, 2, 1, 11, 1, 1, 11, 1, 1, 2, 11, 1, 11, 1, 1, 11, 11, 1, 1, 2, 1, 11,
        1, 1, 2, 11, 1, 1, 11, 11, 11, 1, 2, 11, 1, 11, 1, 1, 1, 1, 1, 1, 2, 1, 11,
        11, 1, 16, 3, 3, 3, 3, 3, 3, 3, 12, 3, 3, 3, 3, 3, 3, 15, 11, 11, 2, 1, 11,
        1, 11, 11, 11, 11, 1, 1, 11, 1, 11, 2, 11, 1, 11, 1, 11, 11, 2, 1, 1, 2, 1, 11,
        11, 1, 1, 1, 11, 11, 1, 11, 1, 1, 2, 11, 1, 1, 11, 1, 1, 2, 1, 11, 2, 1, 1,
        11, 11, 11, 1, 11, 1, 11, 1, 11, 1, 2, 1, 1, 1, 11, 11, 1, 2, 11, 1, 2, 1, 1,
        1, 1, 11, 11, 11, 11, 1, 11, 11, 11, 2, 11, 1, 1, 11, 11, 11, 2, 11, 11, 2, 11, 1,
        11, 1, 1, 1, 1, 1, 1, 1, 11, 11, 2, 11, 1, 11, 11, 11, 11, 2, 1, 1, 2, 11, 1,
        1, 1, 11, 11, 1, 11, 11, 1, 1, 11, 2, 1, 11, 11, 1, 1, 1, 2, 11, 11, 2, 11, 1,
        11, 11, 11, 1, 11, 1, 1, 11, 1, 1, 16, 3, 3, 3, 3, 3, 3, 17, 11, 11, 2, 1, 11,
        11, 1, 11, 1, 11, 1, 1, 11, 11, 1, 1, 11, 11, 1, 1, 1, 11, 1, 11, 1, 2, 11, 11,
        1, 1, 1, 11, 11, 11, 1, 11, 1, 11, 11, 11, 1, 1, 11, 1, 11, 11, 11, 11, 2, 11, 11,
        1, 1, 11, 11, 1, 11, 1, 1, 1, 11, 11, 14, 3, 3, 3, 3, 3, 3, 3, 3, 17, 1, 1,
        1, 1, 11, 1, 1, 11, 1, 1, 11, 11, 11, 2, 1, 1, 11, 11, 1, 1, 11, 1, 11, 1, 1,
        19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Objets",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 17,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1016.34,
          y = 3013,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "",
          type = "",
          shape = "rectangle",
          x = 901.667,
          y = 3002,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 19,
          name = "",
          type = "",
          shape = "rectangle",
          x = 787.333,
          y = 3016.67,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 20,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1083.27,
          y = 2994.17,
          width = 56,
          height = 56,
          rotation = 28.9885,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 22,
          name = "",
          type = "",
          shape = "rectangle",
          x = 845.667,
          y = 3010.33,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704.667,
          y = 3018,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 28,
          name = "",
          type = "",
          shape = "rectangle",
          x = 662,
          y = 3128,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 29,
          name = "",
          type = "",
          shape = "rectangle",
          x = 642,
          y = 3069.5,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 30,
          name = "",
          type = "",
          shape = "rectangle",
          x = 654.5,
          y = 2999.5,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 31,
          name = "",
          type = "",
          shape = "rectangle",
          x = 644,
          y = 3196,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 50,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "",
          type = "",
          shape = "rectangle",
          x = 572,
          y = 2860,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 36,
          name = "",
          type = "",
          shape = "rectangle",
          x = 493.333,
          y = 2749.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 37,
          name = "",
          type = "",
          shape = "rectangle",
          x = 578.667,
          y = 2684,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 38,
          name = "",
          type = "",
          shape = "rectangle",
          x = 572,
          y = 3006.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 39,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1210.67,
          y = 2316,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 85,
          visible = true,
          properties = {}
        },
        {
          id = 40,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1222.67,
          y = 2445.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 85,
          visible = true,
          properties = {}
        },
        {
          id = 41,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1208,
          y = 2572,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 85,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1077.33,
          y = 2309.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 85,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1225.33,
          y = 2506.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 80,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1226.67,
          y = 2692,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 80,
          visible = true,
          properties = {}
        },
        {
          id = 45,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1138.67,
          y = 2310.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 80,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1213.33,
          y = 2753.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 83,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1214.67,
          y = 2797.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 83,
          visible = true,
          properties = {}
        },
        {
          id = 48,
          name = "",
          type = "",
          shape = "rectangle",
          x = 526,
          y = 2806,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "",
          shape = "rectangle",
          x = 848.667,
          y = 1775.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "",
          shape = "rectangle",
          x = 972.667,
          y = 1771.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "",
          shape = "rectangle",
          x = 983.333,
          y = 1652.67,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "",
          type = "",
          shape = "rectangle",
          x = 915.333,
          y = 1456.67,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "",
          type = "",
          shape = "rectangle",
          x = 846,
          y = 1522,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1168.67,
          y = 1398,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "",
          type = "",
          shape = "rectangle",
          x = 843.333,
          y = 1202,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1160.67,
          y = 1128.67,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 57,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1274.67,
          y = 1405.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1278.67,
          y = 1277.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1026.67,
          y = 1412,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "",
          shape = "rectangle",
          x = 833.333,
          y = 1662.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 1786.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "",
          shape = "rectangle",
          x = 893.333,
          y = 1156,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1274.67,
          y = 1149.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 65,
          name = "",
          type = "",
          shape = "rectangle",
          x = 836,
          y = 1346.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "",
          type = "",
          shape = "rectangle",
          x = 962.667,
          y = 1728,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1729.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "",
          shape = "rectangle",
          x = 956,
          y = 1601.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1089.33,
          y = 1417.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "",
          shape = "rectangle",
          x = 822.667,
          y = 1280,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1074.67,
          y = 1161.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1213.33,
          y = 1404,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "",
          shape = "rectangle",
          x = 898.667,
          y = 1214.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 74,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1256,
          y = 1214.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 75,
          name = "",
          type = "",
          shape = "rectangle",
          x = 828,
          y = 1597.33,
          width = 40,
          height = 56,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 76,
          name = "",
          type = "",
          shape = "rectangle",
          x = 834.667,
          y = 1470.67,
          width = 40,
          height = 56,
          rotation = 0,
          gid = 41,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "",
          type = "",
          shape = "rectangle",
          x = 844,
          y = 1405.33,
          width = 40,
          height = 56,
          rotation = 0,
          gid = 43,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "",
          type = "",
          shape = "rectangle",
          x = 970.667,
          y = 1525.33,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "",
          type = "",
          shape = "rectangle",
          x = 978.667,
          y = 1462.67,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "",
          type = "",
          shape = "rectangle",
          x = 958.667,
          y = 1396,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1285.33,
          y = 1341.33,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 52,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "",
          shape = "rectangle",
          x = 968,
          y = 1141.33,
          width = 48,
          height = 48,
          rotation = 0,
          gid = 48,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1012,
          y = 1152,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 83,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1213.33,
          y = 1145.33,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "",
          shape = "rectangle",
          x = 646.667,
          y = 2952,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 87,
          name = "",
          type = "",
          shape = "rectangle",
          x = 574.667,
          y = 2757.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 88,
          name = "",
          type = "",
          shape = "rectangle",
          x = 509.333,
          y = 2881.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 89,
          name = "",
          type = "",
          shape = "rectangle",
          x = 574.667,
          y = 2938.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 90,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1208,
          y = 3004.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 91,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1221.33,
          y = 2634.67,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 92,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232.67,
          y = 2372.67,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 93,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1164.67,
          y = 2999.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 94,
          name = "",
          type = "",
          shape = "rectangle",
          x = 966,
          y = 3003.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 95,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1232.67,
          y = 2867.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 96,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1219,
          y = 2944.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 97,
          name = "",
          type = "",
          shape = "rectangle",
          x = 129.333,
          y = 190.667,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 98,
          name = "",
          type = "",
          shape = "rectangle",
          x = 260,
          y = 192,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 99,
          name = "",
          type = "",
          shape = "rectangle",
          x = 444,
          y = 188,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 61,
          visible = true,
          properties = {}
        },
        {
          id = 100,
          name = "",
          type = "",
          shape = "rectangle",
          x = 338,
          y = 182,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 101,
          name = "",
          type = "",
          shape = "rectangle",
          x = 194,
          y = 183.333,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 102,
          name = "",
          type = "",
          shape = "rectangle",
          x = 386,
          y = 175.333,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 103,
          name = "",
          type = "",
          shape = "rectangle",
          x = 590,
          y = 2610,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 104,
          name = "",
          type = "",
          shape = "rectangle",
          x = 599.333,
          y = 2559.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 66,
          visible = true,
          properties = {}
        },
        {
          id = 105,
          name = "",
          type = "",
          shape = "rectangle",
          x = 582.667,
          y = 2492,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 49,
          visible = true,
          properties = {}
        },
        {
          id = 106,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1014.67,
          y = 2304,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 50,
          visible = true,
          properties = {}
        },
        {
          id = 107,
          name = "",
          type = "",
          shape = "rectangle",
          x = 946.667,
          y = 2304,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 50,
          visible = true,
          properties = {}
        },
        {
          id = 108,
          name = "",
          type = "",
          shape = "rectangle",
          x = 769.333,
          y = 2305.33,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 50,
          visible = true,
          properties = {}
        },
        {
          id = 109,
          name = "",
          type = "",
          shape = "rectangle",
          x = 836,
          y = 2304.67,
          width = 64,
          height = 44,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 110,
          name = "",
          type = "",
          shape = "rectangle",
          x = 897.667,
          y = 2292.33,
          width = 64,
          height = 44,
          rotation = 0,
          gid = 60,
          visible = true,
          properties = {}
        },
        {
          id = 113,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 114,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 1984,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 115,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 116,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 2112,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 117,
          name = "",
          type = "",
          shape = "rectangle",
          x = 192,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 118,
          name = "",
          type = "",
          shape = "rectangle",
          x = 256,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 119,
          name = "",
          type = "",
          shape = "rectangle",
          x = 320,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 120,
          name = "",
          type = "",
          shape = "rectangle",
          x = 384,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 121,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 122,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 123,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 124,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 125,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 2112,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 126,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 127,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1984,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 128,
          name = "",
          type = "",
          shape = "rectangle",
          x = 512,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 129,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "",
          type = "",
          shape = "rectangle",
          x = 576,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "",
          shape = "rectangle",
          x = 640,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 133,
          name = "",
          type = "",
          shape = "rectangle",
          x = 704,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 134,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 135,
          name = "",
          type = "",
          shape = "rectangle",
          x = 832,
          y = 1984,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 136,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 137,
          name = "",
          type = "",
          shape = "rectangle",
          x = 896,
          y = 2112,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 138,
          name = "",
          type = "",
          shape = "rectangle",
          x = 960,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 139,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 2112,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 140,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1024,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 141,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 1984,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 142,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1088,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 144,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1280,
          y = 1984,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 145,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1344,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 146,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 1920,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 147,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 1984,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 148,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 2048,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 149,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 2112,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 150,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1408,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 152,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1216,
          y = 2176,
          width = 56,
          height = 56,
          rotation = 0,
          gid = 51,
          visible = true,
          properties = {}
        },
        {
          id = 153,
          name = "",
          type = "",
          shape = "rectangle",
          x = 448,
          y = 2176,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 154,
          name = "",
          type = "",
          shape = "rectangle",
          x = 893.333,
          y = 2177.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 155,
          name = "",
          type = "",
          shape = "rectangle",
          x = 768,
          y = 2177.33,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 156,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1351.33,
          y = 2159.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 157,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1296.67,
          y = 2164.67,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 158,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1086.67,
          y = 2176,
          width = 64,
          height = 64,
          rotation = 0,
          gid = 87,
          visible = true,
          properties = {}
        },
        {
          id = 159,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1167.33,
          y = 2166,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 160,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1034,
          y = 2167.33,
          width = 36,
          height = 36,
          rotation = 0,
          gid = 88,
          visible = true,
          properties = {}
        },
        {
          id = 161,
          name = "",
          type = "",
          shape = "rectangle",
          x = 838.667,
          y = 2170.67,
          width = 48,
          height = 48,
          rotation = 0,
          gid = 44,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 4,
      name = "Ennemis",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 163,
          name = "",
          type = "",
          shape = "rectangle",
          x = 658.228,
          y = 2548.8,
          width = 46,
          height = 42,
          rotation = 268.586,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 165,
          name = "",
          type = "",
          shape = "rectangle",
          x = 805.106,
          y = 2924.05,
          width = 46,
          height = 42,
          rotation = 302.961,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 166,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1014.22,
          y = 2915.11,
          width = 46,
          height = 42,
          rotation = 270.287,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 167,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1168.14,
          y = 2867.85,
          width = 46,
          height = 42,
          rotation = 221.825,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 168,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1165.13,
          y = 2334.43,
          width = 46,
          height = 42,
          rotation = 139.414,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 169,
          name = "",
          type = "",
          shape = "rectangle",
          x = 775.61,
          y = 2344.03,
          width = 46,
          height = 42,
          rotation = 59.773,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 170,
          name = "",
          type = "",
          shape = "rectangle",
          x = 11.6667,
          y = 2743.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 171,
          name = "",
          type = "",
          shape = "rectangle",
          x = 138.333,
          y = 2742.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 172,
          name = "",
          type = "",
          shape = "rectangle",
          x = 269,
          y = 2743.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 173,
          name = "",
          type = "",
          shape = "rectangle",
          x = 393,
          y = 2743.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 174,
          name = "",
          type = "",
          shape = "rectangle",
          x = 331.667,
          y = 2701,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 175,
          name = "",
          type = "",
          shape = "rectangle",
          x = 203.667,
          y = 2694.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 176,
          name = "",
          type = "",
          shape = "rectangle",
          x = 79.6667,
          y = 2695.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 177,
          name = "",
          type = "",
          shape = "rectangle",
          x = 269,
          y = 2103.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 178,
          name = "",
          type = "",
          shape = "rectangle",
          x = 330.333,
          y = 2103.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 179,
          name = "",
          type = "",
          shape = "rectangle",
          x = 457,
          y = 2101,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 180,
          name = "",
          type = "",
          shape = "rectangle",
          x = 398.333,
          y = 2102.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 181,
          name = "",
          type = "",
          shape = "rectangle",
          x = 905,
          y = 1914.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 182,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1030.33,
          y = 1914.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 183,
          name = "",
          type = "",
          shape = "rectangle",
          x = 966.333,
          y = 1914.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 184,
          name = "",
          type = "",
          shape = "rectangle",
          x = 903.667,
          y = 1975.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 185,
          name = "",
          type = "",
          shape = "rectangle",
          x = 967.667,
          y = 1974.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 186,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1031.67,
          y = 1973,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 187,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1093,
          y = 1525,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 188,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1159.67,
          y = 1526.33,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 189,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1223.67,
          y = 1527.67,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        },
        {
          id = 190,
          name = "",
          type = "",
          shape = "rectangle",
          x = 1290.33,
          y = 1525,
          width = 46,
          height = 42,
          rotation = 0,
          gid = 89,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "imagelayer",
      image = "",
      id = 5,
      name = "Decorations",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      repeatx = false,
      repeaty = false,
      properties = {}
    }
  }
}
